# Generated by Django 2.1.7 on 2019-03-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('mode_of_payment', models.CharField(choices=[('DC', 'DEBIT CARD'), ('CC', 'CREDIT CARD'), ('NB', 'NET BANKING')], max_length=2)),
            ],
        ),
    ]
