# Generated by Django 2.1.7 on 2019-03-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_remove_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
