# Generated by Django 2.1.7 on 2019-03-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20190316_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='donation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
