# Generated by Django 2.1.7 on 2019-03-17 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20190317_0518'),
        ('donations', '0005_auto_20190317_0027'),
    ]

    operations = [
    ]
