# Generated by Django 2.1.7 on 2019-03-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_college', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
